name: Build/release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  build-windows:
    runs-on: "windows-latest"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install
      
      - name: Build application
        run: npm run build-win

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Upload Windows artifacts
          path: |
            dist/Deeeep.io-Reef-Client-${{ github.event.inputs.version }}-win.exe

  build-mac:
    runs-on: "macos-latest"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install
      
      - name: Build application
        run: npm run build-mac

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Upload macOS artifacts
          path: |
            dist/Deeeep.io-Reef-Client-${{ github.event.inputs.version }}-mac.dmg

  build-linux:
    runs-on: "ubuntu-latest"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install
      
      - name: Build application
        run: npm run build-linux

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Upload Linux artifacts
          path: |
            dist/Deeeep.io-Reef-Client-${{ github.event.inputs.version }}-linux.AppImage
        